CM
c=======================================================================
c     The values below depend on package/version
c
      character*3 li_prefix
      character*50 package
      integer mjor_vers_n
      integer mnor_vers_n
      integer mjor_rv_n
      integer mnor_rv_n
      parameter (
     &     li_prefix = 'EMS',
     &     package =
     &     'Edinburgh Management Science Optimization Library ',
     &     mjor_vers_n = 0,
     &     mnor_vers_n = 2,
     &     mjor_rv_n =   16,
     &     mnor_rv_n =   0)
