CM
      integer ix_msg_fq
      integer ix_ems_wr_cn
      integer ix_usr_mx_n_u
      integer ix_n_si_it
      integer ix_mx_n_si_it
      integer ix_rsmi_msg_msk
      integer ix_mx_n_r
      integer ix_mx_n_c
      integer ix_ml_nm_n_ch
      integer ix_dvx_mode
      integer ix_it_usr_xit_fq
      integer ix_n_el_in_aux_blk
      integer ix_n_aux_blk
      integer ix_n_pg_li
      integer ix_n_r
      integer ix_n_c
      integer ix_n_pr_ifs
      integer ix_n_du_ifs
      integer ix_wr_ml_da_msk
      integer ix_wr_ml_st_msk
      integer ix_mx_n_el_in_aux_blk
      integer ix_wr_li_ln
      integer ix_mx_nd_n
      integer ix_i_lp_msg_msk
      integer ix_mx_n_nd
      integer ix_mx_n_i_fs_sol
      integer ix_n_i_fs_sol
      integer ix_n_i_vr
      integer ix_n_sos_se
      integer ix_n_i_vr_no_i
      integer ix_prob_st
      integer ix_wr_rg_da_msk
      integer ix_mx_n_i_vr
      integer ix_mx_n_sos_se
      integer ix_i_alg
      integer ix_mx_n_i_da_en
      integer ix_crsh_msk
      integer ix_crsh_tl_dl_pri
      integer ix_crsh_fn_dn
      integer ix_ems_er_cn
 
      integer ix_ts_parsmi
 
      integer ix_ems_fi_wr_msk
      integer ix_scl_mode
      integer ix_scl_bd
      integer ix_mx_n_a_el
      integer ix_n_a_el
      integer ix_ml_blk_st_msk
      integer ix_ml_da_st_msk
      integer ix_ml_da_no_cg_msk
      integer ix_du_sol_mode
      integer ix_ml_nm_n_rl
      integer ix_sslv_en_msk
      integer ix_sslv_xit_msk
      integer ix_n_bs
      integer ix_n_reset
      integer ix_rq_reset
      integer ix_u_pc
      integer ix_r_pc
      integer ix_eta_fi_mode_msk
      integer ix_eta_fi_da_st_msk
      integer ix_pc_alg
      integer ix_n_dvx_it
      integer ix_mn_n_dvx_it
      integer ix_n_dvx_fwk
      integer ix_r_du_act_sgn
      integer ix_inv_alg_msk
      integer ix_inv_msg_msk
      integer ix_inv_log_msk
      integer ix_inv_mx_n_eta
      integer ix_inv_mx_n_eta_el
      integer ix_n_inv_sing
      integer ix_u_bs_cg
      integer ix_rq_inv
      integer ix_sto_ftran_ix_mode
      integer ix_sto_btran_ix_mode
      integer ix_sto_tbu_r_ix_mode
      integer ix_sto_ftran_ix
      integer ix_sto_btran_ix
      integer ix_sto_tbu_r_ix
      integer ix_tbu_r_loop_mode
      integer ix_bwd_tran_dse_rhs_n_r
      integer ix_fwd_tran_dse_rhs_n_r
      integer ix_dse_tbu_r_n_c
      integer ix_usr_cz_c_msk
      integer ix_usr_cz_r_msk
      integer ix_l1_cz_r_mx_n_cdd
      integer ix_n_pc_vr
      integer ix_n_pc_el
      integer ix_n_non_bc_pr_ifs
      integer ix_rq_re_pc
      integer ix_cz_c_msk
      integer ix_cz_r_msk
      integer ix_u_bs_mode
      integer ix_sto_u_eta_v_mode
      integer ix_u_bs
      integer ix_sto_u_eta_v
      integer ix_sto_u_eta_se_ty
      integer ix_mx_n_u
      integer ix_n_u
      integer ix_lo_sto_mode
      integer ix_asm_msk
      integer ix_ck_msk
      integer ix_it_o_sw_fm_wr_df
      integer ix_it_o_sw_fm_ck_df
      integer ix_wr_lp_da
      integer ix_wr_bs_fq
      integer ix_g_tt_da
      integer ix_g_it_tt_fq
      integer ix_g_it_tt_ivl
      integer ix_mx_n_bc_pr_act_rfn_it
      integer ix_mx_n_reset_pi_rfn_it
      integer ix_mx_n_pv_c_rfn_it
      integer ix_mx_n_full_pi_rfn_it
      integer ix_mx_n_u_pi_rfn_it
      integer ix_eta_fi_n_grp
      integer ix_eta_fi_n_inv_grp
      integer ix_eta_fi_n_se
      integer ix_eta_fi_n_inv_se
      integer ix_eta_fi_n_eta
      integer ix_eta_fi_n_inv_eta
      integer ix_eta_fi_n_v
      integer ix_eta_fi_n_inv_v
      integer ix_eta_fi_n_ix
      integer ix_eta_fi_n_inv_ix
      integer ix_mx_n_pwl_vr
      integer ix_mx_n_pwl_vr_da_en
      integer ix_repl_non_std_vr_mode_msk
      integer ix_repl_non_std_vr_st_msk
      integer ix_n_bp_vr
      integer ix_n_pwl_vr
      integer ix_n_pwl_vr_da_en
      integer ix_cu_is_n
      integer ix_cu_ml_n
      integer ix_ml_blk_mv_k
      integer ix_ds_n_en_m1
      integer ix_is_n_en_m1
      integer ix_ns_n_en_m1
      integer ix_sv_ml_ct_vr
 
      integer ix_n_lo_c_eta
      integer ix_n_lo_r_eta
      integer ix_n_lo_r_eta_el
      integer ix_n_up_r_eta
      integer ix_n_up_r_eta_el
      integer ix_n_sus_eta_srch_op_cf
      integer ix_sus_eta_srch_al_t_ls_ix_lm
      integer ix_sus_eta_srch_ls_t_buk_ix_lm
      integer ix_sus_eta_srch_dbl_n_buk_ix_lm
      integer n_ems_i_ct_vr
      integer n_osl_i_ct_vr
 
      parameter (ix_msg_fq =                1)
      parameter (ix_ems_wr_cn =             2)
      parameter (ix_usr_mx_n_u =            3)
      parameter (ix_n_si_it =               4)
      parameter (ix_mx_n_si_it =            5)
      parameter (ix_rsmi_msg_msk =          6)
      parameter (ix_mx_n_r =                9)
      parameter (ix_mx_n_c =               10)
      parameter (ix_ml_nm_n_ch =           11)
      parameter (ix_dvx_mode =             17)
      parameter (ix_it_usr_xit_fq =        20)
      parameter (ix_n_el_in_aux_blk =      23)
      parameter (ix_n_aux_blk =            24)
      parameter (ix_n_pg_li =              26)
      parameter (ix_n_r =                  27)
      parameter (ix_n_c =                  28)
      parameter (ix_n_pr_ifs =             29)
      parameter (ix_n_du_ifs =             30)
      parameter (ix_wr_ml_da_msk =         32)
      parameter (ix_wr_ml_st_msk =         33)
      parameter (ix_mx_n_el_in_aux_blk =   34)
      parameter (ix_wr_li_ln =             36)
      parameter (ix_mx_nd_n =              37)
      parameter (ix_i_lp_msg_msk =         38)
      parameter (ix_mx_n_nd =              40)
      parameter (ix_mx_n_i_fs_sol =        41)
      parameter (ix_n_i_fs_sol =           42)
      parameter (ix_n_i_vr =               43)
      parameter (ix_n_sos_se =             44)
      parameter (ix_n_i_vr_no_i =          45)
      parameter (ix_prob_st =              47)
      parameter (ix_wr_rg_da_msk =         49)
      parameter (ix_mx_n_i_vr =            50)
      parameter (ix_mx_n_sos_se =          51)
      parameter (ix_i_alg =                52)
      parameter (ix_mx_n_i_da_en =         53)
 
      parameter (ix_crsh_msk =             60)
      parameter (ix_crsh_tl_dl_pri =       ix_crsh_msk + 1)
      parameter (ix_crsh_fn_dn =           ix_crsh_tl_dl_pri + 1)
 
      parameter (ix_ems_er_cn =            70)
      parameter (ix_ts_parsmi =            71)
 
      parameter (ix_ems_fi_wr_msk =        80)
      parameter (ix_scl_mode =             ix_ems_fi_wr_msk + 1)
      parameter (ix_scl_bd =               ix_scl_mode + 1)
      parameter (ix_mx_n_a_el =            ix_scl_bd + 1)
      parameter (ix_n_a_el =               ix_mx_n_a_el + 1)
      parameter (ix_ml_blk_st_msk =        ix_n_a_el + 1)
      parameter (ix_ml_da_st_msk =         ix_ml_blk_st_msk + 1)
      parameter (ix_ml_da_no_cg_msk =      ix_ml_da_st_msk + 1)
      parameter (ix_du_sol_mode =          ix_ml_da_no_cg_msk + 1)
      parameter (ix_ml_nm_n_rl =           ix_du_sol_mode + 1)
 
      parameter (ix_sslv_en_msk =          90)
      parameter (ix_sslv_xit_msk =         ix_sslv_en_msk + 1)
      parameter (ix_n_bs =                 ix_sslv_xit_msk + 1)
      parameter (ix_n_reset =              ix_n_bs + 1)
      parameter (ix_rq_reset =             ix_n_reset + 1)
 
      parameter (ix_u_pc =                 100)
      parameter (ix_r_pc =                 ix_u_pc + 1)
      parameter (ix_eta_fi_mode_msk =      ix_r_pc + 1)
      parameter (ix_eta_fi_da_st_msk =     ix_eta_fi_mode_msk + 1)
      parameter (ix_mn_n_dvx_it =          ix_eta_fi_da_st_msk + 1)
      parameter (ix_pc_alg =               ix_mn_n_dvx_it + 1)
      parameter (ix_n_dvx_it =             ix_pc_alg + 1)
      parameter (ix_n_dvx_fwk =            ix_n_dvx_it + 1)
      parameter (ix_r_du_act_sgn =         ix_n_dvx_fwk + 1)
 
      parameter (ix_inv_alg_msk =          110)
      parameter (ix_inv_msg_msk =          ix_inv_alg_msk + 1)
      parameter (ix_inv_log_msk =          ix_inv_msg_msk + 1)
      parameter (ix_inv_mx_n_eta =         ix_inv_log_msk + 1)
      parameter (ix_inv_mx_n_eta_el =      ix_inv_mx_n_eta + 1)
      parameter (ix_n_inv_sing =           ix_inv_mx_n_eta_el + 1)
      parameter (ix_u_bs_cg =              ix_n_inv_sing + 1)
      parameter (ix_rq_inv =               ix_u_bs_cg + 1)
 
      parameter (ix_sto_ftran_ix_mode =    120)
      parameter (ix_sto_btran_ix_mode =    ix_sto_ftran_ix_mode + 1)
      parameter (ix_sto_tbu_r_ix_mode =    ix_sto_btran_ix_mode + 1)
      parameter (ix_tbu_r_loop_mode =      ix_sto_tbu_r_ix_mode + 1)
      parameter (ix_sto_ftran_ix =         ix_tbu_r_loop_mode + 1)
      parameter (ix_sto_btran_ix =         ix_sto_ftran_ix + 1)
      parameter (ix_sto_tbu_r_ix =         ix_sto_btran_ix + 1)
      parameter (ix_bwd_tran_dse_rhs_n_r = ix_sto_tbu_r_ix + 1)
      parameter (ix_fwd_tran_dse_rhs_n_r = ix_bwd_tran_dse_rhs_n_r + 1)
      parameter (ix_dse_tbu_r_n_c =        ix_fwd_tran_dse_rhs_n_r + 1)
 
      parameter (ix_usr_cz_c_msk =         130)
      parameter (ix_usr_cz_r_msk =         ix_usr_cz_c_msk + 1)
      parameter (ix_l1_cz_r_mx_n_cdd =     ix_usr_cz_r_msk + 1)
      parameter (ix_n_pc_vr =              ix_l1_cz_r_mx_n_cdd + 1)
      parameter (ix_n_pc_el =              ix_n_pc_vr + 1)
      parameter (ix_n_non_bc_pr_ifs =      ix_n_pc_el + 1)
      parameter (ix_rq_re_pc =             ix_n_non_bc_pr_ifs + 1)
      parameter (ix_cz_c_msk =             ix_rq_re_pc + 1)
      parameter (ix_cz_r_msk =             ix_cz_c_msk + 1)
 
      parameter (ix_u_bs_mode =            140)
      parameter (ix_sto_u_eta_v_mode =     ix_u_bs_mode + 1)
      parameter (ix_u_bs =                 ix_sto_u_eta_v_mode + 1)
      parameter (ix_sto_u_eta_v =          ix_u_bs + 1)
      parameter (ix_sto_u_eta_se_ty =      ix_sto_u_eta_v + 1)
      parameter (ix_mx_n_u =               ix_sto_u_eta_se_ty + 1)
      parameter (ix_n_u =                  ix_mx_n_u + 1)
 
      parameter (ix_lo_sto_mode =          150)
      parameter (ix_asm_msk =              ix_lo_sto_mode + 1)
      parameter (ix_ck_msk =               ix_asm_msk + 1)
      parameter (ix_it_o_sw_fm_wr_df =     ix_ck_msk + 1)
      parameter (ix_it_o_sw_fm_ck_df =     ix_it_o_sw_fm_wr_df + 1)
      parameter (ix_wr_lp_da =             ix_it_o_sw_fm_ck_df + 1)
      parameter (ix_wr_bs_fq =             ix_wr_lp_da + 1)
 
      parameter (ix_g_tt_da =              160)
      parameter (ix_g_it_tt_fq =           ix_g_tt_da + 1)
      parameter (ix_g_it_tt_ivl =          ix_g_it_tt_fq + 1)
 
      parameter (ix_mx_n_bc_pr_act_rfn_it = 170)
      parameter (ix_mx_n_reset_pi_rfn_it = ix_mx_n_bc_pr_act_rfn_it + 1)
      parameter (ix_mx_n_pv_c_rfn_it =     ix_mx_n_reset_pi_rfn_it + 1)
      parameter (ix_mx_n_full_pi_rfn_it =  ix_mx_n_pv_c_rfn_it + 1)
      parameter (ix_mx_n_u_pi_rfn_it =     ix_mx_n_full_pi_rfn_it + 1)
 
      parameter (ix_eta_fi_n_grp =         180)
      parameter (ix_eta_fi_n_inv_grp =     ix_eta_fi_n_grp + 1)
      parameter (ix_eta_fi_n_se =          ix_eta_fi_n_inv_grp + 1)
      parameter (ix_eta_fi_n_inv_se =      ix_eta_fi_n_se + 1)
      parameter (ix_eta_fi_n_eta =         ix_eta_fi_n_inv_se + 1)
      parameter (ix_eta_fi_n_inv_eta =     ix_eta_fi_n_eta + 1)
      parameter (ix_eta_fi_n_v =           ix_eta_fi_n_inv_eta + 1)
      parameter (ix_eta_fi_n_inv_v =       ix_eta_fi_n_v + 1)
      parameter (ix_eta_fi_n_ix =          ix_eta_fi_n_inv_v + 1)
      parameter (ix_eta_fi_n_inv_ix =      ix_eta_fi_n_ix + 1)
 
      parameter (ix_mx_n_pwl_vr =          190)
      parameter (ix_mx_n_pwl_vr_da_en =    ix_mx_n_pwl_vr + 1)
      parameter (ix_repl_non_std_vr_mode_msk =
     &     ix_mx_n_pwl_vr_da_en + 1)
      parameter (ix_repl_non_std_vr_st_msk =
     &     ix_repl_non_std_vr_mode_msk + 1)
      parameter (ix_n_bp_vr =             ix_repl_non_std_vr_st_msk + 1)
      parameter (ix_n_pwl_vr =            ix_n_bp_vr + 1)
      parameter (ix_n_pwl_vr_da_en =      ix_n_pwl_vr + 1)
 
      parameter (ix_cu_is_n =              200)
      parameter (ix_cu_ml_n =              ix_cu_is_n + 1)
      parameter (ix_ml_blk_mv_k =          ix_cu_ml_n + 1)
      parameter (ix_ds_n_en_m1 =           ix_ml_blk_mv_k + 1)
      parameter (ix_is_n_en_m1 =           ix_ds_n_en_m1 + 1)
      parameter (ix_ns_n_en_m1 =           ix_is_n_en_m1 + 1)
      parameter (ix_sv_ml_ct_vr =          ix_ns_n_en_m1 + 1)
 
      parameter (ix_n_lo_c_eta =           210)
      parameter (ix_n_lo_r_eta =           ix_n_lo_c_eta + 1)
      parameter (ix_n_lo_r_eta_el =        ix_n_lo_r_eta + 1)
      parameter (ix_n_up_r_eta =           ix_n_lo_r_eta_el + 1)
      parameter (ix_n_up_r_eta_el =        ix_n_up_r_eta + 1)
      parameter (ix_n_sus_eta_srch_op_cf =  ix_n_up_r_eta_el + 1)
      parameter (ix_sus_eta_srch_al_t_ls_ix_lm =
     &     ix_n_sus_eta_srch_op_cf + 1)
      parameter (ix_sus_eta_srch_ls_t_buk_ix_lm =
     &     ix_sus_eta_srch_al_t_ls_ix_lm + 1)
      parameter (ix_sus_eta_srch_dbl_n_buk_ix_lm =
     &     ix_sus_eta_srch_ls_t_buk_ix_lm + 1)
 
      parameter (n_ems_i_ct_vr =           250)
      parameter (n_osl_i_ct_vr =            71)
